<?php
return  array (
  'TMPL_PARSE_STRING' => 
  array (
    '__UPLOAD__' => '/Uploads',
  ),
  'SHOW_PAGE_TRACE' => true,
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'dswenda',
  'DB_USER' => 'root',
  'DB_PWD' => 'root',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'ds_',
  'DB_CHARSET' => 'utf8',
  'ANSWER' => '2',
  'ASK' => '1',
  'ACCEPT' => '2',
  'DEL_ANSWER' => '3',
  'DEL_ASK' => '3',
  'DEL_ACCEPT_ASK' => '2',
  'DEL_ACCEPT_ANSWER' => '2',
  'LV_LOGIN' => '1',
  'LV_ASK' => '5',
  'LV_ANSWER' => '1',
  'LV_ADOPT' => '2',
  'LV1' => '300',
  'LV2' => '11',
  'LV3' => '25',
  'LV4' => '50',
  'LV5' => '100',
  'LV6' => '125',
  'LV7' => '150',
  'LV8' => '175',
  'LV9' => '200',
  'LV10' => '225',
  'LV11' => '250',
  'LV12' => '300',
  'WEBNAME' => '得声问答',
  'KEYWORDS' => '得声 问答 校园',
  'DISCRIPTION' => '校园生活互动问答社区',
  'COPY' => 'Copyright © 2016 jeski.Com All Rights Reserved 得声问答',
  'RECORD' => '京ICP备',
  'RES_ON' => '1',
  'WEB_ON' => '1',
);