-- MySQL Script generated by MySQL Workbench
-- 11/12/15 15:54:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dswenda
-- -----------------------------------------------------
-- 得声校园问答系统数据库
DROP SCHEMA IF EXISTS `dswenda` ;

-- -----------------------------------------------------
-- Schema dswenda
--
-- 得声校园问答系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dswenda` DEFAULT CHARACTER SET utf8 ;
USE `dswenda` ;

-- -----------------------------------------------------
-- Table `dswenda`.`ds_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_role` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_role` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色id',
  `role_name` VARCHAR(20) NOT NULL DEFAULT '',
  `role_auth_ca` VARCHAR(60) NOT NULL DEFAULT '',
  `role_auth_ids` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`role_id`))
ENGINE = MyISAM
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_admin` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT COMMENT '管理员id',
  `admin_account` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '管理员账号',
  `admin_pwd` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '管理员密码',
  `logintime` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上一次登录时间',
  `loginip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '上次登录的ip',
  `lock` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '1:锁定 0:解锁',
  `admin_role_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`admin_id`),
  INDEX `admin_acount` (`admin_account` ASC),
  INDEX `fk_ds_admin_ds_role1_idx` (`admin_role_id` ASC))
ENGINE = MyISAM
COMMENT = '后台管理员表';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_user` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户的id号',
  `account` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户账号',
  `nickname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户昵称',
  `pwd` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户密码',
  `face` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '用户的头像',
  `answer` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户回答问题数',
  `adopt` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户问题采纳数',
  `ask` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户提问数',
  `coin` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户金币数',
  `experince` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户经验值',
  `logintime` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上次登录时间',
  `loginip` VARCHAR(20) NOT NULL DEFAULT '',
  `register` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '注册时间',
  `lock` TINYINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '1:锁定 0:未锁定',
  PRIMARY KEY (`id`),
  INDEX `account` (`account` ASC))
ENGINE = MyISAM
COMMENT = '前台用户';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_category` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父id  0:顶级分类',
  PRIMARY KEY (`id`),
  INDEX `pid` (`pid` ASC))
ENGINE = MyISAM
COMMENT = '分类';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_ask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_ask` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_ask` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '问题的内容',
  `reward` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '回答问题的奖励值',
  `solve` TINYINT(1) UNSIGNED NULL DEFAULT 0 COMMENT '1:解决 0：未解决',
  `time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '提问时间',
  `answer` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '回答数',
  `uid` INT UNSIGNED NOT NULL COMMENT '所属用户的id',
  `cid` INT UNSIGNED NOT NULL COMMENT '所属分类',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC),
  INDEX `cid` (`cid` ASC))
ENGINE = MyISAM
COMMENT = '问题表';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_answer` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL DEFAULT '',
  `adopt` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是够被采纳1:采纳 0:未被采纳',
  `time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '回答时间',
  `aid` INT UNSIGNED NOT NULL COMMENT '所属问题id',
  `uid` INT UNSIGNED NOT NULL COMMENT '所属用户的id',
  PRIMARY KEY (`id`),
  INDEX `adopt` (`adopt` ASC),
  INDEX `aid` (`aid` ASC),
  INDEX `fk_ds_answer_ds_user1_idx` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '答案表';


-- -----------------------------------------------------
-- Table `dswenda`.`ds_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dswenda`.`ds_auth` ;

CREATE TABLE IF NOT EXISTS `dswenda`.`ds_auth` (
  `auth_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auth_name` VARCHAR(45) NOT NULL DEFAULT '',
  `auth_level` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `auth_pid` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `auth_c` VARCHAR(45) NOT NULL DEFAULT '',
  `auth_a` VARCHAR(45) NOT NULL DEFAULT '',
  `auth_path` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`auth_id`))
ENGINE = MyISAM
COMMENT = '权限表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
